# Generated by Django 2.2.1 on 2019-07-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20190711_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mod_date',
        ),
    ]
