# Generated by Django 2.2.1 on 2019-07-11 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20190711_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='danwei',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mod_date',
        ),
        migrations.AddField(
            model_name='project',
            name='Innovation',
            field=models.TextField(default='创新点', verbose_name='创新点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='applicant',
            field=models.CharField(default='工程管理部', max_length=45, verbose_name='申报单位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='apply_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='申请时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.FloatField(default=10000.87, verbose_name='总预算'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='complete_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='结束时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='excution',
            field=models.TextField(default='组织实施', verbose_name='实施方式'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='purpose',
            field=models.TextField(default='目标', verbose_name='目的'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='leader',
            field=models.CharField(max_length=10, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectname',
            field=models.CharField(max_length=45, verbose_name='项目名称'),
        ),
    ]
