# Generated by Django 2.2.1 on 2019-07-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_auto_20190713_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='personnumber',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='参与人数'),
        ),
    ]
