# Generated by Django 2.2.1 on 2019-07-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_auto_20190713_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='applicant',
            field=models.CharField(default='', max_length=30, verbose_name='申报单位'),
        ),
        migrations.AlterField(
            model_name='project',
            name='apply_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectid',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectname',
            field=models.CharField(default='', max_length=30, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sort',
            field=models.CharField(choices=[(1, '技术开发'), (2, '技术引进'), (3, '基础研究'), (4, '软科学研究'), (5, '推广应用')], default=1, max_length=45, verbose_name='项目分类'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[(1, '编制中'), (2, '审核中'), (3, '通过归档')], default=1, max_length=20, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(choices=[(1, '2019年度'), (2, '2020年度'), (3, '2021年度'), (4, '2022年度'), (5, '2023年度')], default=1, max_length=20, verbose_name='申报年度'),
        ),
    ]
