# Generated by Django 2.2.1 on 2019-07-19 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0011_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(default='', max_length=50, unique=True, verbose_name='单位名称')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='applicant',
        ),
        migrations.AlterField(
            model_name='project',
            name='sort',
            field=models.CharField(choices=[('1', '技术开发'), ('2', '技术引进'), ('3', '基础研究'), ('4', '软科学研究'), ('5', '推广应用')], default=1, max_length=45, verbose_name='项目分类'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', '编制中'), ('2', '审核中'), ('3', '通过归档')], default=1, max_length=20, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(choices=[('1', '2019年度'), ('2', '2020年度'), ('3', '2021年度'), ('4', '2022年度'), ('5', '2023年度')], default=1, max_length=20, verbose_name='申报年度'),
        ),
        migrations.AddField(
            model_name='project',
            name='applicant_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todolist.branch'),
        ),
    ]
